# Generated by Django 4.2.7 on 2023-11-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(default='Invalid', max_length=150, unique=True)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
