# Generated by Django 4.2.7 on 2023-11-28 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
    ]
