# Generated by Django 4.2.7 on 2023-12-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='Invalid', max_length=150, unique=True),
        ),
    ]
